show_entries:
    path: /entries
    defaults: { _controller: BlogBlogAplicationBundle:Entry:showAll }

show_entry:
    path: /entry/{id}
    defaults: { _controller: BlogBlogAplicationBundle:Entry:showEntry,id:1 }
